[project]
name = "radar_parlamentar_mcp"
version = "0.1.0"
description = "MCP Server for Brazilian National Congress"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1,<2",
    "pymupdf>=1.26.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
radar_parlamentar_mcp = "radar_parlamentar_mcp.mcp_server:main"